name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger auf den Main-Branch. Du kannst dies auch auf andere Branches anpassen.

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:latest

    - name: Pull the latest Docker image on the server (deployment server)
      run: |
        # Login to GitHub Container Registry again to pull the latest image
        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GH_USERNAME }} --password-stdin

        # Pull the latest image from the GitHub Container Registry
        docker pull ghcr.io/${{ github.repository }}:latest

    - name: Stop and remove the old container (if it exists)
      run: |
        docker stop myportfolio-container || true
        docker rm myportfolio-container || true

    - name: Run the new container with the latest image
      run: |
        docker run -d --name myportfolio-container -p 80:80 ghcr.io/${{ github.repository }}:latest
