name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Oder dein Branch (z. B. 'master' oder 'main')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout des Repositories
    - name: Checkout repository
      uses: actions/checkout@v2

    # Docker Build und Push
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/myportfolio/my-html-app:latest .

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/myportfolio/my-html-app:latest